export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const INCREASE = "INCREASE"
export const DECREASE = "DECREASE"
export const FROM_LOCALE = "FROM_LOCALE"
export const CLEAR = "CLEAR"
export const SET_TOTAL = "SET_TOTAL"
