export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_SUB_CAT = 'SET_SUB_CAT'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_MIN_PRICE = 'SET_MIN_PRICE'
export const SET_MAX_PRICE = 'SET_MAX_PRICE'
export const RESET = 'RESET'
export const ERROR = 'ERROR'
