export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const FETCH_ALL = 'FETCH_ALL'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const ITEMS_LOADING = 'ITEMS_LOADING'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'